name: Ruby Tests

on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.1', '3.1.1', '3.2.1', '3.3.1', '3.4.1']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: '2.5.23'
    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake
